######################################
#### manual configuration example: ###
#Twitter:
#  access_token: XXX-XXX
#  access_token_secret: XXX
#  consumer_key: XXX
#  consumer_secret: XXX
#
#Discord:
#  - IncludeReplyToUser: false
#    IncludeRetweet: false
#    IncludeUserReply: true
#    custom_message: 'A new tweet!'
#    keyword_sets:
#    - - 'League'    # tweet will be posted if tweet contains all 3 words {League of Legends}, no particular order.
#      - 'of'
#      - 'Legends'
#    - - 'Dota 2'    # tweet will be posted if tweet contains 'Dota 2' in this specific order
#    - - 'MOBA'      # tweet will be posted if it contains 'MOBA'
#    twitter_ids:
#    - '123'         # define as many as you want with a dash {-} at the beginning
#    - '456'
#    twitter_handles:
#    - 'discordapp'
#    twitter_lists:
#    - 'https://twitter.com/rokxx/lists/dota-2'
#    webhook_urls:
#    - 'https://discordapp.com/api/webhooks/123456/XXXX-XXXX'
######################################

# configuration through environment variables
Twitter:
  access_token: 1291600484931780608-7qedEXag15N1LnPtnKRiJnYCC6I9i8
  access_token_secret: qpdn0l2XYFERvz7zLEnJqN0v4GBABPk6gvRmuVMtOiDTr
  consumer_key: YUnJAwNdF9gZDC0uHEvDFSs6J
  consumer_secret: u5kfTCIvaB029H0SO8DBIUFyqErzvgPhTdRGVX4cZLwFr8FA5e

Discord:
- IncludeReplyToUser: false
    IncludeRetweet: false
    IncludeUserReply: true
    custom_message: 'A new tweet!'
    keyword_sets:
     - - '400 Mawozo'    
     - - 'Haiti'    # tweet will be posted if tweet contains 'Dota 2'. A tweet saying `2day we play Dota` will not be posted.
    track:
     - 'python'
    webhook_urls:
     - 'https://discord.com/api/webhooks/918681869699121212/Dyn3vaOgkrDCDZ2xsFuMaJLnehFV6arVexbCKM6TmObiK8ejutdcBXgwLfQ_Ua22cQjH'
  - track:
     - 'python'
    webhook_urls:
     - 'https://discord.com/api/webhooks/918681869699121212/Dyn3vaOgkrDCDZ2xsFuMaJLnehFV6arVexbCKM6TmObiK8ejutdcBXgwLfQ_Ua22cQjH'

  
